version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: Application
    volumes:
     - /Storage/Web Development/MySQL:/var/lib/mysql