version: '2'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: Application
    volumes:
     - ./MySQL:/var/lib/mysql
