version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - /Storage/Web Development/Server/Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /Storage/Web Development:/app
    ports:
      - 80:80